### ISSUE TITLE
AnsiCast Error

### ISSUE THREAD

**Issue by ambaricloud** [lakekeeper/lakekeeper#672]
SPARK_VERSION = pyspark.__version__
SPARK_MINOR_VERSION = '.'.join(SPARK_VERSION.split('.')[:2])
SPARK_MINOR_VERSION
ICEBERG_VERSION = "1.6.1"
config = {
    "spark.sql.defaultCatalog": "warehouse",
    "spark.sql.catalog.warehouse": "org.apache.iceberg.spark.SparkCatalog",
    "spark.sql.catalog.warehouse.type": "rest",
    "spark.sql.catalog.warehouse.uri": "http://localhost:8181/catalog/",
    "spark.sql.catalog.warehouse.warehouse": "my-warehouse",
    "spark.sql.catalog.warehouse.token": "<>",
    "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions",
    "spark.jars.packages": f"""org.apache.iceberg:iceberg-spark-runtime-{SPARK_MINOR_VERSION}_2.12:{ICEBERG_VERSION},org.apache.iceberg:iceberg-aws-bundle:{ICEBERG_VERSION}"""
}
spark_config = SparkConf().setMaster('local').setAppName("Iceberg-REST")
for k, v in config.items():
    spark_config = spark_config.set(k, v)

spark = SparkSession.builder.config(conf=spark_config).getOrCreate()

spark.sql("USE warehouse")
ERROR>>>>
Py4JJavaError: An error occurred while calling o44.sql.
: java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/expressions/AnsiCast
	at org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions.$anonfun$apply$6(IcebergSparkSessionExtensions.scala:54)
	at org.apache.spark.sql.SparkSessionExtensions.$anonfun$buildResolutionRules$1(SparkSessionExtensions.scala:215)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.SparkSessionExtensions.buildResolutionRules(SparkSessionExtensions.scala:215)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.customResolutionRules(BaseSessionStateBuilder.scala:222)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anon$1.<init>(BaseSessionStateBuilder.scala:194)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.analyzer(BaseSessionStateBuilder.scala:185)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.$anonfun$build$2(BaseSessionStateBuilder.scala:375)
	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:92)
	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:77)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:691)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.expressions.AnsiCast
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 46 more

**Comment by c-thiel** [comment]
Did you actually specify "spark.sql.catalog.warehouse.token": "<>", ?
My guess is that it is the problem. As you can see in the Callstack, this is not a Lakekeeper issue but fails before Lakekeeeper is contacted.

Please try to use code boxes. These free text issues are very hard to read.

**Comment by ambaricloud** [comment]
Yes, I have used token value. Removed it before posting in git because of
its long value.  bTW, same spark jar files  works for minimal docker, as
per lake keeper document.

Regards,

"This email is completely written by a human (Satya Kondapalli)"
*Satya Kondapalli*

*Cell: *630-340-9704* | ***@***.**** | **ambaricloud.com
<http://ambaricloud.com> *
YouTube: ***@***.***/videos

**Comment by c-thiel** [comment]
Please post the exact steps here to reproduce, we won't be able to help otherwise.

**Comment by ambaricloud** [comment]
Hi Christian
Attached are the minimal/access-control Docker test scripts for your reference.

[Lakekeeper_REST_WITH_RBAC_v2.md](https://github.com/user-attachments/files/18141136/Lakekeeper_REST_WITH_RBAC_v2.md)
[Lakekeeper_REST_NO_RBAC.md](https://github.com/user-attachments/files/18141137/Lakekeeper_REST_NO_RBAC.md)

**Comment by c-thiel** [comment]
Hey @ambaricloud, I can't reproduce the error you show. To be honest it looks like a broken spark setup on your side. You are using a really old spark Version (3.3.2). Could you update to 3.5 or later?

**Comment by ambaricloud** [comment]
Changed Spark 3.3 to Spark 3.5 and is working. Thank you @c-thiel
